name: remote_control

services:
  api:
    image: remote-control-device:latest
    container_name: remote-control-device
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_started
      rabbitmq:
        condition: service_healthy
        restart: true

  db:
    image: postgres:18.4-alpine3.23
    container_name: postgres-database
    env_file: ./db/.env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql

  rabbitmq:
    image: rabbitmq:4.3.2-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    env_file: .env
    ports:
      - 5672:5672
      - 15672:15672
    configs:
      - source: rabbitmq-plugins
        target: /etc/rabbitmq/enabled_plugins
    volumes:
      - rabbitmq-conf:/etc/rabbitmq/
      - rabbitmq-lib:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5672"]
      interval: 5s
      timeout: 15s
      retries: 3

volumes:
  pg_data:
  rabbitmq-lib:
  rabbitmq-log:
  rabbitmq-conf:

configs:
  rabbitmq-plugins:
    content: "[rabbitmq_management]."  
