apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: remote-control
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/george-haddad/remote-control-device.git"
    targetRevision: HEAD
    path: "k8s"
    directory:
      recurse: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: remote-control
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
