apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: remote-control-gateway
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: remote-control-gateway
  namespace: remote-control
spec:
  gatewayClassName: remote-control-gateway
  listeners:
    - name: http
      protocol: HTTP
      port: 80
